### ISSUE TITLE
SDWebImageCompletionBlock doesn't work anymore

### ISSUE THREAD

**Issue by Alexookah** [ZuYuanZhou/testSD#2]
I am not sure but i think the latest 8.3 ios upgrade has made some changes on which SDWebImageCompletionBlock doesn't run anymore.

This is the error i am getting. Why is this happening
Function signature '(UIImage!, NSError!, SDImageCacheType!, NSURL!) -> Void' is not compatible with expected type '@objc_block (UIImage!, NSError!, SDImageCacheType, NSURL!) -> Void'

**Comment by ZuYuanZhou** [comment]
it's just because swift update, to the error, just change SDImageCacheType! to SDImageCacheType will fix.

**Comment by ZuYuanZhou** [comment]
Also, you can delete all the functions in AppDelegate.swift, just leave if like bellow:

import UIKit


class AppDelegate: UIResponder, UIApplicationDelegate {

	var window: UIWindow?
}

**Comment by ZuYuanZhou** [comment]
@Alexookah Code pushed. Pls check

**Comment by Alexookah** [comment]
Issue is fixed, Thank you
